In [9]:
import pandas as pd 
import seaborn as sns

In [30]:
var = sns.load_dataset("penguins").head(100)
df = pd.DataFrame(var)

In [31]:
print("Orignal Data Set\n")
df

Orignal Data Set

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
95,Adelie,Dream,40.8,18.9,208.0,4300.0,Male
96,Adelie,Dream,38.1,18.6,190.0,3700.0,Female
97,Adelie,Dream,40.3,18.5,196.0,4350.0,Male
98,Adelie,Dream,33.1,16.1,178.0,2900.0,Female
99,Adelie,Dream,43.2,18.5,192.0,4100.0,Male

In [39]:
df['bill_length_mm'] = df['bill_length_mm'].fillna(df['bill_length_mm'].mean())
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())
df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean())
df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].mean())
df['sex'] = df['sex'].fillna("Not Specified")
print("Edited Data Set:") 
df  # As You Can See The Difference Between Orignal Data Set And Edited Data Set Nan Values Are Edited Now But We Cannot Calculate The Mean Of A
    # Categorical Value Thats Why I Passed A String.

Edited Data Set:

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.100000,18.700000,181.000000,3750.000000,Male
1,Adelie,Torgersen,39.500000,17.400000,186.000000,3800.000000,Female
2,Adelie,Torgersen,40.300000,18.000000,195.000000,3250.000000,Female
3,Adelie,Torgersen,38.690909,18.476768,188.838384,3719.444444,Not Specified
4,Adelie,Torgersen,36.700000,19.300000,193.000000,3450.000000,Female
...,...,...,...,...,...,...,...
95,Adelie,Dream,40.800000,18.900000,208.000000,4300.000000,Male
96,Adelie,Dream,38.100000,18.600000,190.000000,3700.000000,Female
97,Adelie,Dream,40.300000,18.500000,196.000000,4350.000000,Male
98,Adelie,Dream,33.100000,16.100000,178.000000,2900.000000,Female
99,Adelie,Dream,43.200000,18.500000,192.000000,4100.000000,Male

In [67]:
# Train, Test, Split, Standard Scaling And Cleaning The Data

data = {
    'Name':['Sahaan','Dayyan','Ayesha','Sudais','Javeria'],
    'Age':[21,18,None,19,21],
    'Class':[15,12,16,13,15],
    'Marks':[50,60,70,80,90],
    'Study Hours':[1,2,3,4,5],
    'Gender':['Male','Male','Female',None,'Female'],
}

df = pd.DataFrame(data)
df

# Step 1: Cleaning The Data:

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Gender'] = df['Gender'].fillna('Not Specified')

print(df)

# Step 2: Label Encoding 

from sklearn.preprocessing import LabelEncoder

df_label = df.copy()
le = LabelEncoder()

df_label['Gender Encoder'] = le.fit_transform(df_label['Gender'])
print(df_label[['Name','Gender','Gender Encoder']])

# Step 3: Standard Scaling

from sklearn.preprocessing import StandardScaler, MinMaxScaler
numerical_columns = ['Age','Marks','Study Hours','Class']
standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(df[numerical_columns])

print("\n Standard Scaling Of DataSet:")
print(pd.DataFrame(standard_scaled,columns=['Age','Marks','Study Hours','Class']))

# Step 4:  Min Max Scaling 

minmax_scaling = MinMaxScaler()
minmax_scaled = minmax_scaling.fit_transform(df[numerical_columns])

print("\n MinMax Scaling")
print(pd.DataFrame(minmax_scaled,columns=['Age','Marks','Study Hours','Class']))

# Step 5 Train, Test, Split The Model:

from sklearn.model_selection import train_test_split

x =df [['Study Hours']]
y =df [['Marks']]

x_train, x_test, y_train, y_test = train_test_split(x,y,  test_size=0.2, random_state=42) 

print("X Training\n", x_train, "\n X Testing\n", x_test)
print("\n Y Training\n", y_train, "\n Y Testing\n", y_test)

      Name    Age  Class  Marks  Study Hours         Gender
0   Sahaan  21.00     15     50            1           Male
1   Dayyan  18.00     12     60            2           Male
2   Ayesha  19.75     16     70            3         Female
3   Sudais  19.00     13     80            4  Not Specified
4  Javeria  21.00     15     90            5         Female
      Name         Gender  Gender Encoder
0   Sahaan           Male               1
1   Dayyan           Male               1
2   Ayesha         Female               0
3   Sudais  Not Specified               2
4  Javeria         Female               0

 Standard Scaling Of DataSet:
        Age     Marks  Study Hours     Class
0  1.075829 -1.414214    -1.414214  0.544331
1 -1.506160 -0.707107    -0.707107 -1.496910
2  0.000000  0.000000     0.000000  1.224745
3 -0.645497  0.707107     0.707107 -0.816497
4  1.075829  1.414214     1.414214  0.544331

 MinMax Scaling
        Age  Marks  Study Hours  Class
0  1.000000   0.00         0.00   0.75
1  0.000000   0.25         0.25   0.00
2  0.583333   0.50         0.50   1.00
3  0.333333   0.75         0.75   0.25
4  1.000000   1.00         1.00   0.75
X Training
    Study Hours
4            5
2            3
0            1
3            4
 X Testing
    Study Hours
1            2

 Y Training
    Marks
4     90
2     70
0     50
3     80
 Y Testing
    Marks
1     60